spring:
  application:
    name: taskqueue

  datasource:
    url: jdbc:postgresql://localhost:5432/taskqueue
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
